### PR TITLE
Add searching to HTML report

### PR DESCRIPTION
**Pull request by joshuaobrien**
A quick, simple way to filter/search through the listed files. I've found myself using ctrl-f quite a bit to search, so I hope this is useful to others 😄 

filter

### CODE REVIEW

**Comment by joshuaobrien** [comment]
Hey @coreyfarrell, thanks for the feedback. Sorry for the huge delay, this completely slipped my mind.

I'll update the PR to handle the case where JS is disabled. 

> incorporated into `assets/sorter.js`

By this, do you mean that I should move `onInput` into `sorter.js`, with the appropriate changes?

**Comment by bcoe** [comment]
@joshuaobrien want to dust this off?

**Comment by joshuaobrien** [comment]
Oops. Was cleaning up my local repo and didn't realise I hadn't branched off master. 😅

**Comment by joshuaobrien** [comment]
Opened a new PR over at #650, @bcoe

**Pull request closed without merging**
