### PR TITLE
Add statements metric as default on html-spa reporter

### PR DESCRIPTION
**Pull request by giovanism**
I propose changing the default option to make it more consistent with other reporters.

### CODE REVIEW

**Comment by bcoe** [comment]
@giovanism can you send me a screen shot of what this ends up looking like?

**Comment by giovanism** [comment]
gambar

That's what I get when I set my `htlm-spa` reporter like this
```js
  coverageReporters: [
    'cobertura',
    [
      'html-spa',
      {
        subdir: 'html-spa',
        metricsToShow: ['statements', 'lines', 'branches', 'functions'],
      },
    ],
    'json',
    'lcov',
    'text',
    'text-summary'
  ],
```
However, I haven't been able to build istanbuljs from source tho

**Comment by zo-1** [comment]
This seems like a great addition - particularly as there's no way to customize the metrics from nyc. Is there any updates on this?

**Comment by giovanism** [comment]
Fair, I'll close this ticket then.

**Pull request closed without merging**
