### PR TITLE
Ignore insignificant lines when coalesce

### LINKED ISSUE #514: Feature Request: Ignore insignificant lines when coalesce ranges
Take the following example code:
```js
if (process.env.NOTSET) {
	console.log('not covered 1');
	console.log('not covered 2');
	console.log('not covered 3');
	/* nothing to cover on this line */
	console.log('also not covered');
}
```

With the release of #511 instead of reporting `2,3,4,6` as uncovered it reports `2-4,6` as uncovered.  This is great, a further improvement would be if we could report `2-6` as uncovered since line 5 is insignificant.  I haven't investigated what it would take to accomplish this but wanted to create a ticket.  This would be especially nice in situations where a larger function is never called and contains lines which do not have any coverage counters.

CC @piranna

### PR DESCRIPTION
**Pull request by piranna**
Fixes #514.

### CODE REVIEW

**Comment by piranna** [comment]
Any update on this? Can be reviewed and merged? :-)

**Comment by coreyfarrell** [comment]
@piranna sorry for the delay, I've been a bit buried lately but I promise I will review this ASAP.

**Comment by piranna** [comment]
> @piranna sorry for the delay, I've been a bit buried lately but I promise I will review this ASAP.

No problem, take your time :-)

**Comment by SimenB** [comment]
Yeah go ahead! I think it's fair not to regard the visual output as covered by semver - we use a lockfile anyways, so CI won't randomly break for us whenever a release is out 👍

**Comment by piranna** [comment]
> This looks good to me, I reviewed each change to the tested text reports.

Thank you for reviewing them :-)

**Comment by coreyfarrell** [comment]
This is published to `istanbul-report@3.0.2`, tagged `next` for now.  I have a PR open for nyc, will probably publish `nyc@15.0.1` to `next` later today.

@piranna very much appreciate your work on this, IMO the updated reports look MUCH better (you can see tap-snapshots changes in the nyc PR).

**Comment by piranna** [comment]
> This is published to `istanbul-report@3.0.2`, tagged `next` for now. I have a PR open for nyc, will probably publish `nyc@15.0.1` to `next` later today.

Great! :-D


> @piranna very much appreciate your work on this, IMO the updated reports look MUCH better (you can see tap-snapshots changes in the nyc PR).

You are welcome :-) I use coverage reports a lot when running Jest tests and was missing to see more missing lines on it and what of them needed more priority (not the best way to do tests, but help to do regression tests). Thank you for accepting it upstream, hope this can be useful for that and to others :-)

**Comment by coreyfarrell** [comment]
`nyc@15.0.1` is now published to `next`.

FYI to immediately use this with jest you should be able to explicitly install `istanbul-reports@3.0.2` to your own project and this should cause jest to use that version (I'm unsure if you'll need to `npm dedupe` or similar if jest already installed 3.0.1).

**Comment by SimenB** [comment]
I can bump in jest

**Comment by SimenB** [comment]
https://github.com/facebook/jest/pull/9758

The changes looks great, awesome job! 👍 

@coreyfarrell any idea how long it'll be tagged as next?

**Comment by coreyfarrell** [comment]
Unless I get an objection I'm probably going to promote it to latest tomorrow.  I just posted a message to our Slack requesting that people test it on projects that do not have 100% coverage.

**Comment by coreyfarrell** [comment]
Updates for both istanbul-reports and nyc are now promoted to `latest`.

**Comment by SimenB** [comment]
Thanks! Merged the Jest PR with updated snapshots now. Not sure when a release will come which forces the update for consumers, but just deleting `istanbul-reports` from any lockfile you might have should download the latest version

**Pull request merged**
