### PR TITLE
feat: add filter to HTML report

### PR DESCRIPTION
**Pull request by joshuaobrien**
Continuation of #519

### CODE REVIEW

**Comment by bcoe** [comment]
@joshuaobrien thank you, I will try to take a look over the weekend.

**Comment by joshuaobrien** [comment]
Any luck, @bcoe?

**Comment by bcoe** [comment]
@joshuaobrien I failed at doing any open source work on the weekend, I'll get this merged as soon as possible, thanks for keeping on top of it.

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
@joshuaobrien works like a charm, thank you for doing this work.

**Pull request merged**
