### PR TITLE
dont skip for loop initialization instrumentation

### PR DESCRIPTION
**Pull request by evanbb**
addresses #187 by removing `skipInit` from the visitor's entry

### CODE REVIEW

**Comment by bcoe** [comment]
removing `skipInit` feels like the right decision to me as well; but let's wait to land this until our next release ... upgrading to Babel 7 might be a little bit rocky, and we don't want to add any more moving parts for Jest.

**Comment by evanbb** [comment]
Makes sense, thanks!

Any idea of an eta for your next release?

**Comment by evanbb** [comment]
@coreyfarrell no worries! Thanks for the update!

**Comment by JaKXz** [comment]
@evanbb sorry about this, would you mind rebasing?

**Comment by evanbb** [comment]
@JaKXz I think I did that correctly (first time doing a rebase 😅) - let me know if that checks out or if you need anything else.

**Comment by JaKXz** [comment]
@evanbb sorry to say but this isn't what you want from a rebase. Would you like to give it another shot? or I can just cherry-pick your commit in a new PR.

**Comment by evanbb** [comment]
@coreyfarrell yep, I thought I was safe to work off master since I was on my fork, but that was definitely the source of some complications - lesson learned :smile:

**Comment by JaKXz** [comment]
I think a feature makes more sense!

**Comment by coreyfarrell** [comment]
@evanbb thank you for the contribution and your patience!

**Pull request merged**
