### PR TITLE
Add support for import.meta.* in istanbul-lib-instrumenter

### PR DESCRIPTION
**Pull request by Westbrook**
The current version of this is a static addition of `import.meta.*` support in the instrumenter with a test specifically for `import.meta.url`. I'd be happy to look into making `plugins` a member of `opts` or moving the test into its own spec as mentioned in the issue as needed. Thanks!

Fixes https://github.com/istanbuljs/istanbuljs/issues/202

### CODE REVIEW

**Comment by Westbrook** [comment]
Ping.

**Comment by coreyfarrell** [comment]
We're holding off on new features until nyc 13 is released as latest on npm.  That said I think I'd prefer the to just allow plugins to be set through options. See #205.

As for making importMeta a default plugin, I'm not sure.  CC @bcoe @JaKXz

**Comment by Westbrook** [comment]
I'm all for #205 as a solution! It would certainly do what I needed with better room to grow over time.

Do you have any insight into when NYC 13 might be released? It would be awesome to see a pre-release with one of these two solutions included, but I understand the complexities that presents. 🤞 on soon!

**Comment by coreyfarrell** [comment]
@Westbrook the plan (assuming no major regressions are uncovered) is to fully release nyc v13 in the next week.  Once that is done I will be able to move forward with some of the currently open PR's, initially I'll be working on non-breaking changes (I believe #205 will be non-breaking).

**Comment by Westbrook** [comment]
Any new news on the NYC release? I've got a chain of PRs I'd love to clean up from here and would be happy to help support where I can.

**Comment by coreyfarrell** [comment]
I've just released NYC 13 so I'm moving forward with some PR's.  #205 has been merged but is not yet published to npm.  I have a couple other patches that are being worked on to be included in the next release.

I'm closing this PR since #205 has been merged.  If you disagree please comment and we can discuss further.

**Pull request closed without merging**
