### PR TITLE
Build/fix travis appveyor

### PR DESCRIPTION
**Pull request by JaKXz**

### CODE REVIEW

**Comment by bcoe** [comment]
@JaKXz want to take another crack at kicking this off, I think the early `9.x` release might have had some problems.

**Comment by JaKXz** [comment]
@bcoe unfortunately looks like we're still waiting on that fix. No idea why node v4 on windows isn't co-operating though :(

**Comment by bcoe** [comment]
@bcoe I believe the fix is supposed to be out this week to npm 👍

**Comment by JaKXz** [comment]
Yay Travis is passing now! Thank you npm folks!

**Comment by bcoe** [comment]
@JaKXz looking good 👍 mind kicking off another appveyor build when you have two seconds; I wonder why the Node 4 build failed.

**Comment by JaKXz** [comment]
@bcoe no dice :(

**Comment by CodeTroopers** [comment]
The error is referenced [here](https://github.com/lerna/lerna/issues/999)

**Comment by bcoe** [comment]
@CodeTroopers, @JaKXz sounds like there's potentially a workaround for this issue in the thread that @CodeTroopers linked to? would love an update to this patch if anyone has a moment.

**Comment by CodeTroopers** [comment]
@bcoe I'm not sure of the need to pass time for this issue. It concern only NodeJS4 and [the end support is in April](https://github.com/nodejs/Release)

**Pull request merged**
