### PR TITLE
Allow ignoring class methods

### PR DESCRIPTION
**Pull request by katerberg**
Currently there is no general way to ignore all class methods with a certain name. It has been problematic when writing code for a project that always has a trivial method to be required to ignore it on each class.

This allows a global ignore of all methods of a certain name.

As this is my first pull request, please let me know if there are any special processes to follow.

Thank you!

### CODE REVIEW

**Comment by katerberg** [comment]
Hello,

I've gotten the travis-ci and coveralls passing, but I'm having a hard time understanding appveyor. I can't seem to replicate the failure of missing `highlight.js` even when getting the correct version of node installed.

Would someone mind helping me finish getting this PR ready?

**Comment by katerberg** [comment]
Hi there, just checking in on this to see what I need to do to move forward.

**Comment by bcoe** [comment]
@katerberg my apologizes for this being left on the wayside for so long, I've been unfortunately dealing with a family tragedy. Could you do me a favor and rebase with master, and we'll work on getting this over the finish line.

**Comment by katerberg** [comment]
@bcoe Done! I'm sorry for the tragedy and hope everything ends up okay.

**Comment by katerberg** [comment]
@bcoe @JaKXz Just checking back in on this. I think I rebased correctly but always worth a second set of eyes :)

**Pull request merged**
