### PR TITLE
fixed: handlebars dep bases on vulnerable version

### PR DESCRIPTION
**Pull request by bug-tape**
See https://nodesecurity.io/advisories/755

### CODE REVIEW

**Comment by rvanlaarhoven** [comment]
You'll probably have to update the package-lock.json as well to pass the builds. See https://github.com/istanbuljs/istanbuljs/blob/master/package-lock.json#L6337

**Comment by nbj** [comment]
I was kinda hoping this would get pushed through relatively quick, but @bug-tape seems awol :(

**Comment by YuriGor** [comment]
I didn't see this PR so I made #294 
As I see here only handlebars was updateted, but there is also an issue with lerna.

**Comment by nbj** [comment]
This PR stagnated, so nice work @YuriGor getting things in order :) How long before it can be tagged?

**Comment by YuriGor** [comment]
Dunno, but hope soon, I want to publish nice release too.

**Comment by bug-tape** [comment]
Sorry, have indeed been busy otherwise. Nice work @YuriGor

**Comment by coreyfarrell** [comment]
Superseded by #294.

**Pull request closed without merging**
