### PR TITLE
fix: do not throw on missing range locations

### PR DESCRIPTION
**Pull request by isaacs**
Fix: #753

### CODE REVIEW

**Comment by isaacs** [comment]
@sashuk It needs a review from a collaborator who didn't write it (ie, not from me), and I believe someone to publish the resulting version, if that isn't set up to work automatically.

I do have commit rights here, but I haven't really been terribly involved with this project, so I don't want to overstep unless @SimenB or @bcoe or someone asks me to.

**Comment by SimenB** [comment]
I always feel like I'm overstepping when doing stuff in this project, but as all the original maintainers are busy, we do what we gotta do 😅

**Review by SimenB — APPROVED** [review]
Probably more defensive than it needs to be, but nothing wrong with that (especially considering the regression 😅)

**Comment by isaacs** [comment]
@SimenB it's your kitten now, no returns no refunds! 😅

Re the defensiveness, yeah, I mean, this is a perfect example of the kind of error that TS would have clearly prevented. I've gotten so used to relying on types for this sort of thing, got kinda lazy in that last patch.  But without them, it's like everything is `any`, and I feel like it's a good idea to assume the worst.

**Comment by sashuk** [comment]
Thank you all!

**Pull request merged**
